name: CI

on:
  push:
    branches: [main]
    paths:
      - 'back/**/*'
      - '.github/workflows/deploy-back.yml' 
defaults:
  run:
    working-directory: back

permissions:
  contents: read
  id-token: write # Needed for auth with Deno Deploy

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
          - macOS-12

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Run tests
        run: deno task test

      - name: Install Danet CLI
        run: deno install --allow-read --allow-write --allow-run --allow-env -n danet https://deno.land/x/danet_cli/main.ts
      - name: Bundle app with danet CLI
        run: danet bundle run.js
      - name: Debug
        run: |
          ls
          pwd
          ls bundle
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: saaskit-api
          entrypoint: run.js
          root: back/bundle
